format_version: 10

pipelines:
  go-weather-ci:
    group: default
    materials:
      repo:
        git: https://github.com/YOUR_USERNAME/go-weather-app.git
        branch: master
    stages:
      - build:
          jobs:
            build-go-image:
              tasks:
                - exec:
                    command: docker
                    arguments: ["build", "-t", "go-weather-app", "."]
                - exec:
                    command: docker
                    arguments: ["images"]
